name: Notificación NTFY al subir a main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "Joaquin Pichardo subio codigo a su rama main. E e e e e e e e e e e e." ntfy.sh/devops-itla
